# Generated by Django 3.2 on 2021-05-15 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MasterEntry', '0002_rename_complinttype_name_complainttype_complainttype_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=50, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='CourseVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv_title', models.CharField(max_length=50, verbose_name='Title')),
                ('cv_video', models.FileField(upload_to='video', verbose_name='Video')),
                ('cv_playlist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MasterEntry.dancecategory', verbose_name='Dance Category:')),
            ],
        ),
    ]
