# Generated by Django 3.2 on 2021-05-22 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor', '0002_rename_coursevideos_coursevideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursevideo',
            name='cv_playlist',
        ),
        migrations.AddField(
            model_name='coursevideo',
            name='cv_playid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Tutor.courseplaylist', verbose_name='Dance Category:'),
        ),
    ]
