# Generated by Django 3.2 on 2021-05-25 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0006_auto_20210526_0020'),
        ('Tutor', '0003_auto_20210522_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursevideo',
            name='cv_playid',
        ),
        migrations.AddField(
            model_name='coursevideo',
            name='cv_course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Administrator.dancecourses', verbose_name='Course'),
        ),
    ]
