# Generated by Django 3.2 on 2021-05-25 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor', '0004_auto_20210526_0020'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CoursePlaylist',
        ),
    ]
