# Generated by Django 3.2 on 2021-05-25 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor', '0005_delete_courseplaylist'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursevideo',
            name='cv_thumbnail',
            field=models.FileField(null=True, upload_to='thumbnail', verbose_name='Thumbnail'),
        ),
    ]
