# Generated by Django 3.2 on 2021-07-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor', '0006_coursevideo_cv_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursevideo',
            name='cv_approve',
            field=models.BooleanField(default=False, null=True, verbose_name='Is approved'),
        ),
        migrations.AddField(
            model_name='coursevideo',
            name='cv_update',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
