# Generated by Django 3.2 on 2021-07-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tutor', '0007_auto_20210712_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursevideo',
            name='cv_approve',
            field=models.BooleanField(default=False, verbose_name='Is approved'),
        ),
    ]
