# Generated by Django 3.2 on 2021-05-13 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MasterEntry', '0002_rename_complinttype_name_complainttype_complainttype_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=20, verbose_name='Name')),
                ('student_contact', models.CharField(max_length=11, verbose_name='Contact')),
                ('student_email', models.EmailField(max_length=50, unique=True, verbose_name='Email')),
                ('student_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1, verbose_name='Gender')),
                ('student_dob', models.DateField(verbose_name='Date of birth')),
                ('student_username', models.CharField(max_length=20, unique=True, verbose_name='Username')),
                ('student_password', models.CharField(max_length=20, unique=True, verbose_name='Password')),
                ('student_reenterpassword', models.CharField(max_length=20, unique=True, verbose_name='Re-enter password')),
                ('student_regdate', models.DateField(verbose_name='student_regdate')),
                ('student_dp', models.ImageField(upload_to='profile', verbose_name='Profile picture')),
                ('student_district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MasterEntry.district', verbose_name='District')),
                ('student_place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MasterEntry.place', verbose_name='Place')),
            ],
        ),
    ]
