# Generated by Django 3.2 on 2021-05-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='student_contact',
            field=models.CharField(max_length=10, verbose_name='Contact'),
        ),
    ]
