# Generated by Django 3.2 on 2021-05-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_remove_studentmodel_student_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='student_regdate',
            field=models.DateField(auto_now_add=True, verbose_name='student_regdate'),
        ),
    ]
