# Generated by Django 3.2 on 2021-05-14 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_alter_studentmodel_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='student_gender',
            field=models.IntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Others')], verbose_name='Gender'),
        ),
    ]
