# Generated by Django 3.2 on 2021-05-15 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0007_alter_studentmodel_student_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='student_dp',
            field=models.FileField(upload_to='profile', verbose_name='Profile picture'),
        ),
    ]
