# Generated by Django 3.2 on 2021-05-25 13:52

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0011_alter_studentmodel_student_dp'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='student_country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
    ]
