# Generated by Django 3.2 on 2021-05-25 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0012_studentmodel_student_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='student_district',
        ),
    ]
