# Generated by Django 3.2 on 2021-05-25 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0013_remove_studentmodel_student_district'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='student_country',
        ),
    ]
