# Generated by Django 3.2 on 2021-05-25 15:36

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('MasterEntry', '0003_dancelevel'),
        ('Accounts', '0014_remove_studentmodel_student_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='student_country',
            field=django_countries.fields.CountryField(default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='student_district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MasterEntry.district', verbose_name='District'),
        ),
    ]
