# Generated by Django 3.2 on 2021-05-25 16:53

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0016_remove_studentmodel_student_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='student_country',
            field=django_countries.fields.CountryField(default=0, max_length=2),
            preserve_default=False,
        ),
    ]
