# Generated by Django 3.2 on 2021-06-02 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0017_studentmodel_student_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_pro', models.BooleanField(default=False)),
                ('paid_date', models.DateField(auto_now_add=True, null=True)),
                ('pro_expiry_date', models.DateField(blank=True, null=True)),
                ('subscription_type', models.CharField(choices=[('F', 'FREE'), ('M', 'MONTHLY'), ('Y', 'YEARLY')], default='FREE', max_length=100)),
                ('Student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.studentmodel', verbose_name='Student')),
            ],
        ),
    ]
