# Generated by Django 3.2 on 2021-06-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0018_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='Student',
            field=models.CharField(max_length=40, null=True, verbose_name='Student'),
        ),
    ]
