# Generated by Django 3.2 on 2021-06-04 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0020_remove_subscription_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='subStudent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.studentmodel', verbose_name='Student'),
        ),
    ]
