# Generated by Django 3.2 on 2021-06-10 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0021_subscription_substudent'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Admin_username', models.CharField(max_length=50)),
                ('Admin_password', models.CharField(max_length=50)),
            ],
        ),
    ]
