# Generated by Django 3.2.2 on 2021-05-09 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MasterEntry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor_name', models.CharField(default=False, max_length=20, verbose_name='Name:')),
                ('tutor_contact', models.CharField(default=False, max_length=11, verbose_name='Conatct:')),
                ('tutor_email', models.EmailField(default=False, help_text='Enter Valid Email', max_length=254, unique=True, verbose_name='Email:')),
                ('tutor_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], default='---Select---', max_length=5, verbose_name='Gender:')),
                ('tutor_photo', models.ImageField(upload_to='TutorPhoto', verbose_name='Tutor Photo:')),
                ('tutor_dob', models.DateField(default=False, verbose_name='Date of Birth:')),
                ('tutor_isactive', models.IntegerField(default=1, help_text='If Value is 1 Tutor is Active and Not Active if 0', verbose_name='Is Active:')),
                ('tutor_username', models.CharField(default=False, max_length=15, unique=True, verbose_name='User name:')),
                ('tutor_password', models.CharField(default=False, max_length=15, unique=True, verbose_name='Password:')),
                ('tutor_dancecategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MasterEntry.dancecategory', verbose_name='Dance Category:')),
                ('tutor_designation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MasterEntry.designation', verbose_name='Designation:')),
                ('tutor_district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MasterEntry.district', verbose_name='District:')),
            ],
        ),
        migrations.CreateModel(
            name='DanceCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(default=False, max_length=20, verbose_name='Name:')),
                ('course_photo', models.ImageField(upload_to='CoursePhoto')),
                ('course_description', models.TextField(verbose_name='Description')),
                ('course_totalfees', models.CharField(default=False, max_length=20, verbose_name='Total Fees:')),
                ('course_downpayment', models.CharField(default=False, help_text='Online Registration Amount:', max_length=20, verbose_name='Down Payment:')),
                ('course_details', models.FileField(upload_to='CourseSyllabus', verbose_name='Course Syllabus:')),
                ('course_remarks', models.TextField(verbose_name='Remarks')),
                ('course_dancecategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MasterEntry.dancecategory', verbose_name='Dance Category:')),
                ('course_tutor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Administrator.tutor', verbose_name='Tutor:')),
            ],
        ),
    ]
