# Generated by Django 3.2 on 2021-05-23 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MasterEntry', '0002_rename_complinttype_name_complainttype_complainttype_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor_name', models.CharField(max_length=20, verbose_name='Name:')),
                ('tutor_contact', models.CharField(max_length=11, verbose_name='Conatct:')),
                ('tutor_email', models.EmailField(help_text='Enter Valid Email', max_length=254, unique=True, verbose_name='Email:')),
                ('tutor_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=5, verbose_name='Gender:')),
                ('tutor_photo', models.ImageField(upload_to='TutorPhoto', verbose_name='Tutor Photo:')),
                ('tutor_dob', models.DateField(verbose_name='Date of Birth:')),
                ('tutor_isactive', models.CharField(choices=[('1', 'Active'), ('0', 'Not Active')], help_text='If Value is 1 Tutor is Active and Not Active if 0', max_length=5, verbose_name='Is Active:')),
                ('tutor_username', models.CharField(max_length=15, unique=True, verbose_name='User name:')),
                ('tutor_password', models.CharField(max_length=15, unique=True, verbose_name='Password:')),
                ('tutor_dancecategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MasterEntry.dancecategory', verbose_name='Dance Category:')),
                ('tutor_designation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MasterEntry.designation', verbose_name='Designation:')),
                ('tutor_district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MasterEntry.district', verbose_name='District:')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=50, verbose_name='News title')),
                ('news_content', models.TextField(verbose_name='News Content')),
                ('news_uploaddate', models.DateField(auto_now_add=True, verbose_name='Upload Date')),
                ('news_poster', models.ImageField(upload_to='news', verbose_name='Poster')),
                ('news_loc', models.CharField(default=0, max_length=50)),
                ('news_date', models.DateField(default=0, verbose_name='Date')),
                ('news_newstype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MasterEntry.newstype', verbose_name='News Type:')),
            ],
        ),
        migrations.CreateModel(
            name='DanceCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=20, verbose_name='Name:')),
                ('course_photo', models.ImageField(upload_to='CoursePhoto')),
                ('course_description', models.TextField(verbose_name='Description')),
                ('course_totalfees', models.CharField(max_length=20, verbose_name='Total Fees:')),
                ('course_downpayment', models.CharField(help_text='Online Registration Amount:', max_length=20, verbose_name='Down Payment:')),
                ('course_details', models.FileField(upload_to='CourseSyllabus', verbose_name='Course Syllabus:')),
                ('course_remarks', models.TextField(verbose_name='Remarks')),
                ('course_dancecategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MasterEntry.dancecategory', verbose_name='Dance Category:')),
                ('course_tutor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Administrator.tutor', verbose_name='Tutor:')),
            ],
        ),
    ]
