# Generated by Django 3.2 on 2021-05-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dancecourses',
            name='course_downpayment',
            field=models.CharField(help_text='Online Registration Amount:', max_length=20, verbose_name='Down Payment:'),
        ),
        migrations.AlterField(
            model_name='dancecourses',
            name='course_name',
            field=models.CharField(max_length=20, verbose_name='Name:'),
        ),
        migrations.AlterField(
            model_name='dancecourses',
            name='course_totalfees',
            field=models.CharField(max_length=20, verbose_name='Total Fees:'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='tutor_contact',
            field=models.CharField(max_length=11, verbose_name='Conatct:'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='tutor_dob',
            field=models.DateField(verbose_name='Date of Birth:'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='tutor_email',
            field=models.EmailField(help_text='Enter Valid Email', max_length=254, unique=True, verbose_name='Email:'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='tutor_gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=5, verbose_name='Gender:'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='tutor_isactive',
            field=models.CharField(choices=[('1', 'Active'), ('0', 'Not Active')], help_text='If Value is 1 Tutor is Active and Not Active if 0', max_length=5, verbose_name='Is Active:'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='tutor_name',
            field=models.CharField(max_length=20, verbose_name='Name:'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='tutor_password',
            field=models.CharField(max_length=15, unique=True, verbose_name='Password:'),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='tutor_username',
            field=models.CharField(max_length=15, unique=True, verbose_name='User name:'),
        ),
    ]
