# Generated by Django 3.2 on 2021-05-23 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MasterEntry', '0003_dancelevel'),
        ('Administrator', '0003_auto_20210523_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='dancecourses',
            name='course_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MasterEntry.dancelevel', verbose_name='Level'),
        ),
    ]
