# Generated by Django 3.2 on 2021-05-25 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0004_dancecourses_course_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dancecourses',
            name='course_details',
        ),
        migrations.RemoveField(
            model_name='dancecourses',
            name='course_remarks',
        ),
    ]
