# Generated by Django 3.2 on 2021-05-25 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MasterEntry', '0007_remove_district_district_country'),
        ('Administrator', '0005_auto_20210525_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dancecourses',
            name='course_downpayment',
        ),
        migrations.RemoveField(
            model_name='dancecourses',
            name='course_totalfees',
        ),
        migrations.AddField(
            model_name='dancecourses',
            name='course_subs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MasterEntry.subscriptiontype', verbose_name='Subscription type'),
        ),
    ]
