# Generated by Django 3.2 on 2021-05-27 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0007_dancecourses_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='dancecourses',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
