# Generated by Django 3.2 on 2021-06-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0008_dancecourses_is_premium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dancecourses',
            name='is_premium',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='tutor_contact',
            field=models.CharField(max_length=11, verbose_name='Contact:'),
        ),
    ]
