# Generated by Django 3.2 on 2021-06-11 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0009_auto_20210611_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dancecourses',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
