# Generated by Django 3.2 on 2021-06-21 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0010_alter_dancecourses_is_premium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='tutor_isactive',
            field=models.CharField(choices=[('1', 'Active'), ('0', 'Not Active')], help_text='If Value is 1 Tutor is Active and Not Active if 0', max_length=5, null=True, verbose_name='Is Active:'),
        ),
    ]
