# Generated by Django 3.2 on 2021-06-21 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0011_alter_tutor_tutor_isactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='tutor_gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=20, verbose_name='Gender:'),
        ),
    ]
