# Generated by Django 3.2 on 2021-07-12 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Administrator', '0012_alter_tutor_tutor_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dancecourses',
            name='course_subs',
        ),
    ]
