# Generated by Django 3.2 on 2021-06-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourites',
            name='fstudent',
            field=models.CharField(max_length=40, null=True, verbose_name='Student'),
        ),
    ]
