# Generated by Django 3.2 on 2021-06-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_alter_favourites_fstudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourites',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
