# Generated by Django 3.2 on 2021-06-02 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0003_favourites_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourites',
            name='slug',
        ),
    ]
