# Generated by Django 3.2 on 2021-06-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0006_videofeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofeedback',
            name='vview',
            field=models.BooleanField(default=False, verbose_name='Is liked'),
        ),
    ]
