# Generated by Django 3.2 on 2021-06-09 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0007_videofeedback_vview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
