# Generated by Django 3.2 on 2021-06-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0008_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofeedback',
            name='vfsend',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Send date'),
        ),
    ]
