# Generated by Django 3.2 on 2021-06-09 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MasterEntry', '0007_remove_district_district_country'),
        ('Student', '0009_videofeedback_vfsend'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='feedcontent',
            field=models.TextField(max_length=300, null=True, verbose_name='Give feedback'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedsend',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Send date'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='feedtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MasterEntry.complainttype', verbose_name='Choose feedback type'),
        ),
    ]
