# Generated by Django 3.2 on 2021-06-09 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0021_subscription_substudent'),
        ('Student', '0010_auto_20210610_0156'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='feedstudent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.studentmodel', verbose_name='Student'),
        ),
    ]
