# Generated by Django 3.2 on 2021-06-22 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0022_adminmodel'),
        ('Tutor', '0006_coursevideo_cv_thumbnail'),
        ('Student', '0012_favourites_is_fav'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentlyWatched',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watchdatetime', models.DateTimeField()),
                ('watchstu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.studentmodel', verbose_name='Student')),
                ('watchvid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Tutor.coursevideo', verbose_name='Video:')),
            ],
        ),
    ]
