# Generated by Django 3.2.2 on 2021-05-09 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complinttype_name', models.CharField(max_length=20, unique=True, verbose_name='Complaint Type')),
            ],
        ),
        migrations.CreateModel(
            name='DanceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dancecategory_name', models.CharField(max_length=20, unique=True, verbose_name='Dance Category')),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation_name', models.CharField(max_length=20, unique=True, verbose_name='Designation')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=20, unique=True, verbose_name='District')),
            ],
        ),
        migrations.CreateModel(
            name='NewsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newstype_name', models.CharField(max_length=20, unique=True, verbose_name='News Type')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=20, unique=True, verbose_name='Place')),
                ('place_district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MasterEntry.district', verbose_name='District')),
            ],
        ),
    ]
