# Generated by Django 3.2 on 2021-05-13 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MasterEntry', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complainttype',
            old_name='complinttype_name',
            new_name='complainttype_name',
        ),
    ]
