# Generated by Django 3.2 on 2021-05-23 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterEntry', '0002_rename_complinttype_name_complainttype_complainttype_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DanceLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dancelevel_name', models.CharField(max_length=20, unique=True, verbose_name='Dance Level')),
            ],
        ),
    ]
