# Generated by Django 3.2 on 2021-05-25 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MasterEntry', '0003_dancelevel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='district_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MasterEntry.country', verbose_name='Country'),
        ),
    ]
