# Generated by Django 3.2 on 2021-05-25 15:49

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('MasterEntry', '0004_auto_20210525_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='country',
            field=django_countries.fields.CountryField(default=0, max_length=2),
            preserve_default=False,
        ),
    ]
