# Generated by Django 3.2 on 2021-05-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterEntry', '0005_country_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subtype', models.CharField(max_length=20, verbose_name='Subscription type')),
            ],
        ),
    ]
