# Generated by Django 3.2 on 2021-05-25 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MasterEntry', '0006_subscriptiontype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='district_country',
        ),
    ]
