# Generated by Django 3.2 on 2021-06-13 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterEntry', '0007_remove_district_district_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='dancecategory',
            name='dancecategory_photo',
            field=models.FileField(null=True, upload_to='Categ_img', verbose_name='Thumbnail'),
        ),
    ]
